### ISSUE TITLE
Conflict with google-service plugin version

### ISSUE THREAD

**Issue by devsienko** [dpa99c/cordova-plugin-request-location-accuracy#48]
Hi, 

the plugin not follow of recomendation from here https://blog.phonegap.com/the-play-services-problem-with-cordova-applications-489c9aeb2e89 and it causes problems like this:

> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

Thank you

**Comment by dpa99c** [comment]
Enabling configuration of the version of Play Services specified by this plugin via a plugin variable is unnecessary since there's already a mechanism to override the version specified by this (or any other) plugin using [cordova-android-play-services-gradle-release](https://github.com/dpa99c/cordova-android-play-services-gradle-release).

This means each plugin does not need to provide its own variable and the user does not to maintain the versions separately.
