### ISSUE TITLE
Cordova.plugins is undefined

### ISSUE THREAD

**Issue by ashutoshvyas** [dpa99c/cordova-plugin-request-location-accuracy#6]
I tried to add this plugin to my cordova project (Visual Studio 2015 Tools for Apache Cordova).

It was installed successfully.

However when I try to run it on an android Device (Samsung Galaxy Note4) running Android 5.1.1 it shows cordova.plugins as undefined and therefore is not able to run the plugin.

Any help ?

Thanks
Ashutosh

**Comment by dpa99c** [comment]
A few things to try:
- Connect the device via USB and use [remote debugging with Chrome Dev Tools](http://geeklearning.io/apache-cordova-and-remote-debugging-on-android/). 
  - Go to "Sources" tab and check if "RequestLocationAccuracy.js" is present. If not, the plugin has not installed correctly - this JS file should be present
  - Otherwise, place a breakpoint on where you're calling `cordova.plugins.locationAccuracy.request()`. Check the contents of the `cordova.plugins` namespace. Maybe another plugin is overwriting it.
- Try building and running the [example project](https://github.com/dpa99c/cordova-plugin-request-location-accuracy-example) to check your build environment works OK with the plugin

**Comment by ashutoshvyas** [comment]
My Bad.

Turns out I was accessing the plugin even before the Device was ready.

Wrapped the call within DeviceReady and it works fine.

Thanks
Ashutosh
